# This is a basic workflow to help you get started with Actions

name: CICD_Demo


on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    #runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet Packages
        #working-directory: ./CICD
        run: nuget restore WebApplication1/WebApplication1.sln
        
      - name: Build Solution
        run: msbuild WebApplication1/WebApplication1.sln /p:Configuration=Release
